Repository Open-Smartwatch/open-smartwatch-os, pull requests merged in 2022-04, with the labels that each got.

#210 Bug/screen server
  Readme.md
  composeScreen.sh
  createScreenshot.sh
  fetchScreen.sh
  include/osw_screenserver.h
  include/osw_ui.h
  include/services/OswServiceTaskWebserver.h
  include/services/OswServiceTasks.h
  src/main.cpp
  src/osw_screenserver.cpp
  src/osw_ui.cpp
  src/services/OswServiceTaskWebserver.cpp
  update.sh
Labels: bug

#214 Apps/watchfaces : fix #213
  src/apps/watchfaces/watchface.cpp
Labels: bug, osw-app

#211 Apps : display goal steps ( Today / Total / Goal )
  include/osw_config_keys.h
  src/apps/watchfaces/watchface.cpp
  src/osw_config_keys.cpp
Labels: enhancement, osw-app, osw-service

#222 Fix Auto sleep Timer on Watchface from Issue #186
  src/apps/main/switcher.cpp
Labels: bug, enhancement, discuss

#221 CI : update parallel compile from language resolve #217
  .github/buildEverything.py
  .github/workflows/test-OSW.yml
  include/locales/README.md
Labels: enhancement, discuss
