Repository Open-Smartwatch/open-smartwatch-os, pull requests merged in 2022-08, with the labels that each got.

#280 HAL: refactoring slice-weekday
  include/apps/watchfaces/OswAppWatchfaceDigital.h
  src/apps/watchfaces/OswAppWatchfaceDigital.cpp
  src/apps/watchfaces/OswAppWatchfaceFitness.cpp
  src/apps/watchfaces/OswAppWatchfaceMix.cpp
Labels: enhancement

#282 Set AP-Password
  include/locales/cs-CZ.h
  include/locales/de-DE.h
  include/locales/en-US.h
  include/locales/fr-FR.h
  include/locales/hu-HU.h
  include/locales/it-IT.h
  include/locales/ko-KR.h
  include/osw_config_keys.h
  include/services/OswServiceTaskWiFi.h
  src/apps/tools/OswAppWebserver.cpp
  src/osw_config_keys.cpp
  src/services/OswServiceTaskWiFi.cpp
Labels: enhancement, osw-app, security

#286 fix list of date possibilities
  include/config_defaults.h
Labels: documentation
