Repository Open-Smartwatch/open-smartwatch-os, pull requests merged in 2022-10, with the labels that each got.

#298 Numeral watchface
  include/apps/watchfaces/OswAppWatchfaceMonotimer.h
  include/apps/watchfaces/OswAppWatchfaceNumerals.h
  include/fonts/FreeMonoBold12pt7b.h
  include/fonts/FreeMonoBold18pt7b.h
  include/fonts/FreeMonoBold9pt7b.h
  src/apps/watchfaces/OswAppWatchfaceMonotimer.cpp
  src/apps/watchfaces/OswAppWatchfaceNumerals.cpp
  src/main.cpp
  src/osw_config_keys.cpp
Labels: enhancement, Watchface

#301 CI: omit arbitrary ci
  .github/workflows/test-EMULATOR.yml
  .github/workflows/test-FEATURE.yml
  .github/workflows/test-OSW.yml
Labels: enhancement

#295 DoubleClick: add double-click
  include/osw_hal.h
  src/apps/watchfaces/OswAppWatchface.cpp
  src/hal/buttons.cpp
Labels: enhancement, emulator

#304 Watchface: setting default watchface in local without web-interface
  src/apps/watchfaces/OswAppWatchface.cpp
Labels: enhancement, osw-app, emulator

#309 Fix for #307
  include/devices/esp32.h
  include/services/OswServiceTaskWiFi.h
  src/devices/esp32.cpp
  src/services/OswServiceTaskWiFi.cpp
Labels: bug, pending for discussion

#311 Low power WiFi for #264
  emulator/include/CPU.h
  emulator/src/CPU.cpp
  include/osw_hal.h
  include/platform/EMULATOR.h
  include/platform/GPS_EDITION_V3_1.h
  include/platform/LIGHT_EDITION_V3_2.h
  include/platform/LIGHT_EDITION_V4_0.h
  include/platform/README.md
  include/services/OswServiceTaskWiFi.h
  src/hal/power.cpp
  src/services/OswServiceTaskWiFi.cpp
Labels: enhancement

#312 Unified logging for #168
  emulator/include/Defines.h
  emulator/include/HardwareSerial.h
  emulator/include/Serial.h
  emulator/include/String.h
  emulator/include/WString.h
  emulator/src/CPU.cpp
  emulator/src/Display.cpp
  emulator/src/IO.cpp
  emulator/src/Preferences.cpp
  emulator/src/tests/logging.cpp
  emulator/src/tests/string.cpp
  include/OswLogger.h
  include/debug_scani2c.h
  include/osw_config.h
  platformio.ini
  scripts/build/prebuild_cppflags.py
  src/OswLogger.cpp
  src/apps/_experiments/magnetometer_calibrate.cpp
  src/apps/main/luaapp.cpp
  src/apps/main/map.cpp
  src/apps/main/switcher.cpp
  src/apps/tools/OswAppBLEMediaCtrl.cpp
  src/apps/tools/OswAppPrintDebug.cpp
  src/devices/bma400.cpp
  src/devices/ds3231mz.cpp
  src/devices/esp32.cpp
  src/hal/buttons.cpp
  src/hal/display.cpp
  src/hal/environment.cpp
  src/hal/esp32/sd_filesystem.cpp
  src/hal/power.cpp
  src/hal/progmem.cpp
  src/hal/sd.cpp
  src/hal/time.cpp
  src/main.cpp
  src/osw_config.cpp
  src/osw_hal.cpp
  src/services/OswServiceManager.cpp
  src/services/OswServiceTaskBLECompanion.cpp
  src/services/OswServiceTaskExample.cpp
  src/services/OswServiceTaskGPS.cpp
  src/services/OswServiceTaskMemMonitor.cpp
  src/services/OswServiceTaskWebserver.cpp
  src/services/OswServiceTaskWiFi.cpp
Labels: enhancement

#313 CI: skip unnecessary actions
  .github/workflows/test-EMULATOR.yml
  .github/workflows/test-FEATURE.yml
  .github/workflows/test-OSW.yml
Labels: enhancement

#315 Bugfix for #200
  include/hal/environment.h
  src/hal/environment.cpp
  src/osw_hal.cpp
Labels: bug
