Repository Open-Smartwatch/open-smartwatch-os, pull requests merged in 2022-07, with the labels that each got.

#256 CI : add BLE github action
  .github/buildEverything.py
  .github/workflows/test-OSW.yml
Labels: enhancement, pending for discussion

#262 Setting Button (TimeOut) Through the Web Interface
  include/apps/main/switcher.h
  include/config_defaults.h
  include/osw_config_keys.h
  include/osw_hal.h
  src/apps/main/stopwatch.cpp
  src/apps/main/switcher.cpp
  src/hal/buttons.cpp
  src/osw_config_keys.cpp
Labels: enhancement

#265 Stopwatch : add overall-time measurement
  include/apps/main/stopwatch.h
  src/apps/main/stopwatch.cpp
Labels: enhancement, osw-app, pending for discussion

#269 HAL : add getStepsAverage
  include/hal/environment.h
  src/apps/tools/OswAppDistStats.cpp
  src/apps/tools/OswAppKcalStats.cpp
  src/apps/tools/OswAppStepStats.cpp
  src/hal/environment.cpp
Labels: enhancement, pending for discussion

#272 Fixed Lightsleep not working properly
  src/apps/main/switcher.cpp
Labels: bug

#263 Bug/esp fleeing time
  include/devices/esp32.h
  src/devices/esp32.cpp
Labels: bug

#250 CI : refactoring action with script
  .github/setMatrix.sh
  .github/workflows/test-FEATURE.yml
  .github/workflows/test-OSW.yml
Labels: enhancement
